export interface ThemePreset {
  name: string;
  label: string;
  variables: Record<string, string>;
  animatedClass?: string;
}

export const presets: ThemePreset[] = [
  {
    name: 'void',
    label: 'Void (Dark)',
    variables: {
      '--bg-color': '#121212',
      '--card-color': '#1e1e1e',
      '--accent-color': '#ffcc00',
      '--text-color': '#ffffff',
      '--border-color': '#333333',
      '--text-muted': '#aaaaaa',
      '--hover-color': '#2a2a2a',
    },
  },
  {
    name: 'solar',
    label: 'Solar (Light)',
    variables: {
      '--bg-color': '#f5f5f5',
      '--card-color': '#ffffff',
      '--accent-color': '#ff8c00',
      '--text-color': '#1a1a1a',
      '--border-color': '#dddddd',
      '--text-muted': '#666666',
      '--hover-color': '#eeeeee',
    },
  },
  {
    name: 'cyberpunk',
    label: 'Cyberpunk (Neon)',
    variables: {
      '--bg-color': '#0a0a0f',
      '--card-color': '#12121a',
      '--accent-color': '#00f0ff',
      '--text-color': '#e0e0ff',
      '--border-color': '#ff00ff',
      '--text-muted': '#8888aa',
      '--hover-color': '#1a1a2e',
    },
  },
  {
    name: 'matrix',
    label: 'Matrix (Green)',
    variables: {
      '--bg-color': '#000000',
      '--card-color': '#0a0f0a',
      '--accent-color': '#00ff41',
      '--text-color': '#00ff41',
      '--border-color': '#003b00',
      '--text-muted': '#008f11',
      '--hover-color': '#001a00',
    },
  },
  {
    name: 'sunset',
    label: 'Sunset (Warm)',
    variables: {
      '--bg-color': '#1a1210',
      '--card-color': '#2a1f1a',
      '--accent-color': '#ff6b35',
      '--text-color': '#ffe4c4',
      '--border-color': '#4a3b32',
      '--text-muted': '#c4a882',
      '--hover-color': '#3a2f28',
    },
  },
  {
    name: 'ocean',
    label: 'Ocean (Deep Blue)',
    variables: {
      '--bg-color': '#0a1628',
      '--card-color': '#112240',
      '--accent-color': '#64ffda',
      '--text-color': '#ccd6f6',
      '--border-color': '#1d4375',
      '--text-muted': '#8892b0',
      '--hover-color': '#1a365d',
    },
  },
  {
    name: 'midnight',
    label: 'Midnight (Navy)',
    variables: {
      '--bg-color': '#0f172a',
      '--card-color': '#1e293b',
      '--accent-color': '#60a5fa',
      '--text-color': '#e2e8f0',
      '--border-color': '#334155',
      '--text-muted': '#94a3b8',
      '--hover-color': '#27354f',
    },
  },
  {
    name: 'cherry',
    label: 'Cherry (Red)',
    variables: {
      '--bg-color': '#1a0a0a',
      '--card-color': '#2a1515',
      '--accent-color': '#ff4d6d',
      '--text-color': '#ffd6e0',
      '--border-color': '#5c2a35',
      '--text-muted': '#b8929a',
      '--hover-color': '#3d1f25',
    },
  },
  {
    name: 'retro',
    label: 'Retro (Amber)',
    variables: {
      '--bg-color': '#1a1a00',
      '--card-color': '#2e2e00',
      '--accent-color': '#ffb000',
      '--text-color': '#ffcc00',
      '--border-color': '#4a4a00',
      '--text-muted': '#999900',
      '--hover-color': '#404000',
    },
  },
  {
    name: 'synthwave',
    label: 'Synthwave (80s)',
    variables: {
      '--bg-color': '#1a0b2e',
      '--card-color': '#240b36',
      '--accent-color': '#ff71ce',
      '--text-color': '#f9f9f9',
      '--border-color': '#b967ff',
      '--text-muted': '#c79ac0',
      '--hover-color': '#330f50',
    },
  },
  {
    name: 'nord',
    label: 'Nord (Arctic)',
    variables: {
      '--bg-color': '#2e3440',
      '--card-color': '#3b4252',
      '--accent-color': '#88c0d0',
      '--text-color': '#eceff4',
      '--border-color': '#4c566a',
      '--text-muted': '#81a1c1',
      '--hover-color': '#434c5e',
    },
  },
  {
    name: 'dracula',
    label: 'Dracula (Purple)',
    variables: {
      '--bg-color': '#282a36',
      '--card-color': '#44475a',
      '--accent-color': '#ff79c6',
      '--text-color': '#f8f8f2',
      '--border-color': '#6272a4',
      '--text-muted': '#bd93f9',
      '--hover-color': '#4a4c5e',
    },
  },
  {
    name: 'tokyo-night',
    label: 'Tokyo Night (Blue)',
    variables: {
      '--bg-color': '#1a1b26',
      '--card-color': '#24283b',
      '--accent-color': '#7aa2f7',
      '--text-color': '#a9b1d6',
      '--border-color': '#414868',
      '--text-muted': '#565f89',
      '--hover-color': '#2f334d',
    },
  },
  {
    name: 'gruvbox',
    label: 'Gruvbox (Warm)',
    variables: {
      '--bg-color': '#282828',
      '--card-color': '#3c3836',
      '--accent-color': '#fe8019',
      '--text-color': '#ebdbb2',
      '--border-color': '#504945',
      '--text-muted': '#a89984',
      '--hover-color': '#504945',
    },
  },
  {
    name: 'forest',
    label: 'Forest (Green)',
    variables: {
      '--bg-color': '#1a2f1a',
      '--card-color': '#2a4a2a',
      '--accent-color': '#90ee90',
      '--text-color': '#e0ffe0',
      '--border-color': '#3d6b3d',
      '--text-muted': '#8fbc8f',
      '--hover-color': '#335533',
    },
  },
  {
    name: 'pastel',
    label: 'Pastel (Soft)',
    variables: {
      '--bg-color': '#f0e6ef',
      '--card-color': '#f8f0f8',
      '--accent-color': '#ff9e9e',
      '--text-color': '#4a4a4a',
      '--border-color': '#e0d0e0',
      '--text-muted': '#8a7a8a',
      '--hover-color': '#e8e0e8',
    },
  },
  {
    name: 'monokai',
    label: 'Monokai (Code)',
    variables: {
      '--bg-color': '#272822',
      '--card-color': '#383830',
      '--accent-color': '#fd971f',
      '--text-color': '#f8f8f2',
      '--border-color': '#49483e',
      '--text-muted': '#75715e',
      '--hover-color': '#4a4a42',
    },
  },
  {
    name: 'terminal',
    label: 'Terminal (Green)',
    variables: {
      '--bg-color': '#0c0c0c',
      '--card-color': '#1a1a1a',
      '--accent-color': '#00ff00',
      '--text-color': '#00ff00',
      '--border-color': '#005500',
      '--text-muted': '#008800',
      '--hover-color': '#1a3300',
    },
  },
  {
    name: 'high-contrast',
    label: 'High Contrast',
    variables: {
      '--bg-color': '#000000',
      '--card-color': '#000000',
      '--accent-color': '#ffff00',
      '--text-color': '#ffffff',
      '--border-color': '#ffffff',
      '--text-muted': '#cccccc',
      '--hover-color': '#1a1a1a',
    },
  },
  {
    name: 'aurora',
    label: 'Aurora (Animated)',
    variables: {
      '--bg-color': '#0f2027',
      '--card-color': '#1a1a2e',
      '--accent-color': '#80cbc4',
      '--text-color': '#ffffff',
      '--border-color': '#2c5364',
      '--text-muted': '#a0b0c0',
      '--hover-color': '#16213e',
    },
    animatedClass: 'theme-aurora',
  },
  {
    name: 'lava',
    label: 'Lava (Animated)',
    variables: {
      '--bg-color': '#1a0a0a',
      '--card-color': '#2a0f0f',
      '--accent-color': '#ff4500',
      '--text-color': '#ffd0b0',
      '--border-color': '#7a1e00',
      '--text-muted': '#b33600',
      '--hover-color': '#3d0c02',
    },
    animatedClass: 'theme-lava',
  },
  {
    name: 'ocean-waves',
    label: 'Ocean Waves (Animated)',
    variables: {
      '--bg-color': '#001f3f',
      '--card-color': '#002a5c',
      '--accent-color': '#0059b3',
      '--text-color': '#cce5ff',
      '--border-color': '#004080',
      '--text-muted': '#66a3d2',
      '--hover-color': '#003366',
    },
    animatedClass: 'theme-ocean-waves',
  },
  {
    name: 'neon-pulse',
    label: 'Neon Pulse (Animated)',
    variables: {
      '--bg-color': '#0a0a0a',
      '--card-color': '#141414',
      '--accent-color': '#ff00ff',
      '--text-color': '#e0e0e0',
      '--border-color': '#ff00ff',
      '--text-muted': '#a0a0a0',
      '--hover-color': '#1e1e1e',
    },
    animatedClass: 'theme-neon-pulse',
  },
  {
    name: 'galaxy',
    label: 'Galaxy (Animated)',
    variables: {
      '--bg-color': '#0b001a',
      '--card-color': '#1a0b2e',
      '--accent-color': '#b967ff',
      '--text-color': '#e6e6fa',
      '--border-color': '#4b0082',
      '--text-muted': '#9370db',
      '--hover-color': '#240b36',
    },
    animatedClass: 'theme-galaxy',
  },
  {
    name: 'custom',
    label: 'Custom Accent',
    variables: {
      '--bg-color': '#121212',
      '--card-color': '#1e1e1e',
      '--accent-color': '#ffcc00',
      '--text-color': '#ffffff',
      '--border-color': '#333333',
      '--text-muted': '#aaaaaa',
      '--hover-color': '#2a2a2a',
    },
  },
];

export const defaultPreset = presets.find((p) => p.name === 'void')!;
